import images from './imageSources';

export const homeScreenFeed = [
  {
    key: '0',
    brand: 'Tommy Hilfiger',
    name: 'Tommy Tommy',
    type: 'jacket',
    size: 'S',
    gender: 'female',
    color: 'orange',
    image: images.img1,
    user: 'Simona Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
  {
    key: '1',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img2,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap + 500',
  },
  {
    key: '2',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img3,
    user: 'Simon Simola',
    location: 'Finland',
    verified: false,
    transaction: 'buy',
  },
  {
    key: '3',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img2,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
  {
    key: '4',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img1,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: false,
    transaction: 'swap',
  },
  {
    key: '5',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img3,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
  {
    key: '6',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img1,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
  {
    key: '7',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img2,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
  {
    key: '8',
    brand: 'Gant',
    name: 'Hampshire',
    type: 'jacket',
    size: 'M',
    gender: 'male',
    color: 'green',
    image: images.img2,
    user: 'Simon Simonen',
    location: 'Germany',
    verified: true,
    transaction: 'swap',
  },
];

export const offeredByIcons = [
  images.icons.icn10,
  images.icons.icn3,
  images.icons.icn11,
];
export const offeredByTexts = [
  "Germany",
  "Verified",
  "More",
];

export const offersFeedIcons = [
  images.icons.icn21,
  images.icons.icn22,
  images.icons.icn20,
  images.icons.icn19,
];
